apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mostafagheta/node_backend
          ports:
            - containerPort: 8000
          env:
            - name: DB_URI
              value: "mongodb://root:password@mongo:27017/mydatabase"  # MongoDB connection string
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: backend
